sudo: false
language: go

go:
  - "1.10.x"
  - "1.x"
  - tip
  - master

git:
  depth: 5
  submodules: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
      go: tip
    - os: windows
      go: "1.x"

install: true

script:
  - python check.py
