sudo: false
language: go

go:
  - "1.10.x"
  - "1.x"
  - master

git:
  depth: 5
  submodules: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
      go: master
    - os: windows
      go: master

install:
  - python --version

script:
  - python check.py
