sudo: false
language: go

go:
  - tip
  - "1.10.x"
  - "1.x"

git:
  depth: 5
  submodules: true

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      go: "1.x"
    - os: windows
      go: "1.x"

install: true

script:
  - python check.py
  - jcms -V
