# https://www.appveyor.com/docs/appveyor-yml/

version: build{build}

branches:
  only:
    - master

max_jobs: 1

image: Ubuntu1804

clone_folder: /usr/go/src/github.com/jrmsdev/jcms
clone_depth: 5

stack:
  - go 1.11
  - go 1.10
  - go 1.9

matrix:
  fast_finish: true

install:
  - git submodule update --init

before_build:
  - go version
  - export GOPATH=/usr/go
  - go env

build_script:
  - go env
  - python build.py

after_build:
  - file build/jcms-*.bin
  - md5sum build/jcms-*.bin >build/jcms-bin-md5sum.txt
  - sha256sum build/jcms-*.bin >build/jcms-bin-sha256sum.txt
  - sha512sum build/jcms-*.bin >build/jcms-bin-sha512sum.txt
  - zip build/jcms-build${APPVEYOR_BUILD_NUMBER}.zip build/jcms-*.bin build/jcms-bin-*.txt
  - unzip -l build/jcms-build${APPVEYOR_BUILD_NUMBER}.zip

artifacts:
  - path: 'build/jcms-*.bin'
  - path: 'build/jcms-bin-*.txt'
  - path: 'build/jcms-build*.zip'

test: off

deploy: off
