# https://www.appveyor.com/docs/appveyor-yml/

version: build{build}

branches:
  only:
    - master

max_jobs: 3

image: Ubuntu1804

clone_folder: /usr/go/src/github.com/jrmsdev/jcms
clone_depth: 5

stack:
  - go tip
  - go 1.11
  - go 1.10
  - go 1.9

matrix:
  fast_finish: true

install:
  - git submodule update --init

before_build:
  - go version
  - export GOPATH=/usr/go
  - go env
  - export JCMS_VERSION=$(go run ./internal/_build/version/main.go)
  - export JCMS_BUILDNAME=jcms-${JCMS_VERSION}-build${APPVEYOR_BUILD_NUMBER}

build_script:
  - python build.py

after_build:
  - file build/jcms-*.bin | sort
  - md5sum build/jcms-*.bin >build/${JCMS_BUILDNAME}-md5sum.txt
  - sha256sum build/jcms-*.bin >build/${JCMS_BUILDNAME}-sha256sum.txt
  - sha512sum build/jcms-*.bin >build/${JCMS_BUILDNAME}-sha512sum.txt
  - mkdir -vp dist
  - cd build && zip ../dist/${JCMS_BUILDNAME}.zip jcms-*.bin ${JCMS_BUILDNAME}-*.txt
  - md5sum dist/${JCMS_BUILDNAME}.zip >dist/${JCMS_BUILDNAME}-md5sum.txt
  - sha256sum dist/${JCMS_BUILDNAME}.zip >dist/${JCMS_BUILDNAME}-sha256sum.txt
  - sha512sum dist/${JCMS_BUILDNAME}.zip >dist/${JCMS_BUILDNAME}-sha512sum.txt

artifacts:
  - path: 'dist/jcms-*.zip'
  - path: 'dist/jcms-*.txt'

test: off

deploy: off
