# https://www.appveyor.com/docs/appveyor-yml/

version: build{build}

branches:
  only:
    - master

max_jobs: 3

image: Ubuntu1804

clone_folder: /usr/go/src/github.com/jrmsdev/jcms
clone_depth: 5

stack: go 1.11

matrix:
  fast_finish: true

install:
  - git submodule update --init

before_build:
  - export GOPATH=/usr/go
  - go version
  - go generate ./...

build_script:
  - export JCMS_VERSION=$(go run ./internal/_build/version/main.go)
  - export JCMS_BUILDNAME=jcms-${JCMS_VERSION}-build${APPVEYOR_BUILD_NUMBER}
  - python build.py --all

after_build:
  - mkdir dist
  - cd build
  - file jcms-*.bin | sort | cut -d ':' -f '2-' | sed 's/^ *//'
  - md5sum jcms-*.bin >${JCMS_BUILDNAME}-bin-md5sum.txt
  - sha256sum jcms-*.bin >${JCMS_BUILDNAME}-bin-sha256sum.txt
  - sha512sum jcms-*.bin >${JCMS_BUILDNAME}-bin-sha512sum.txt
  - zip ../dist/${JCMS_BUILDNAME}.zip jcms-*.bin ${JCMS_BUILDNAME}-bin-*sum.txt
  - cd ../dist
  - md5sum ${JCMS_BUILDNAME}.zip >${JCMS_BUILDNAME}-md5sum.txt
  - sha256sum ${JCMS_BUILDNAME}.zip >${JCMS_BUILDNAME}-sha256sum.txt
  - sha512sum ${JCMS_BUILDNAME}.zip >${JCMS_BUILDNAME}-sha512sum.txt
  - cd ..

artifacts:
  - path: 'dist/jcms-*.zip'
  - path: 'dist/jcms-*.txt'

test_script:
  - go test ./...

deploy: off
