# https://www.appveyor.com/docs/appveyor-yml/

version: build{build}

branches:
  only:
    - master

max_jobs: 3

image: Ubuntu1804

clone_folder: /usr/go/src/github.com/jrmsdev/jcms
clone_depth: 5

stack:
  - go 1.11
  - go 1.10
  - go 1.9

matrix:
  fast_finish: true

install:
  - git submodule update --init

before_build:
  - go version
  - export GOPATH=/usr/go
  - go env
  - export JCMS_VERSION=$(go run ./internal/_build/version/main.go)
  - export JCMS_BUILDNAME=jcms-${JCMS_VERSION}-build${APPVEYOR_BUILD_NUMBER}

build_script:
  - python build.py

after_build:
  - mkdir dist
  - cd build
  - file jcms-*.bin | sort
  - md5sum jcms-*.bin >${JCMS_BUILDNAME}-md5sum.txt
  - sha256sum jcms-*.bin >${JCMS_BUILDNAME}-sha256sum.txt
  - sha512sum jcms-*.bin >${JCMS_BUILDNAME}-sha512sum.txt
  - zip ../dist/${JCMS_BUILDNAME}.zip jcms-*.bin ${JCMS_BUILDNAME}-*.txt
  - cd ../dist
  - md5sum ${JCMS_BUILDNAME}.zip >${JCMS_BUILDNAME}-md5sum.txt
  - sha256sum ${JCMS_BUILDNAME}.zip >${JCMS_BUILDNAME}-sha256sum.txt
  - sha512sum ${JCMS_BUILDNAME}.zip >${JCMS_BUILDNAME}-sha512sum.txt
  - cd ..

artifacts:
  - path: 'dist/jcms-*.zip'
  - path: 'dist/jcms-*.txt'

test: off

deploy: off
