# https://www.appveyor.com/docs/appveyor-yml/

version: build{build}

branches:
  only:
    - master

max_jobs: 1

image: Ubuntu1804

clone_folder: /usr/go/src/github.com/jrmsdev/jcms
clone_depth: 5

stack:
  - go 1.11
  - go 1.10
  - go 1.9

matrix:
  fast_finish: true

install:
  - git submodule update --init

before_build:
  - env | sort
  - go version
  - export GOPATH=/usr/go
  - go env

build_script:
  - python build.py

after_build:
  - file build/jcms-*.bin
  - md5sum build/jcms-*.bin >build/jcms-build${APPVEYOR_BUILD_NUMBER}-md5sum.txt
  - sha256sum build/jcms-*.bin >build/jcms-build${APPVEYOR_BUILD_NUMBER}-sha256sum.txt
  - sha512sum build/jcms-*.bin >build/jcms-build${APPVEYOR_BUILD_NUMBER}-sha512sum.txt
  - zip jcms-build${APPVEYOR_BUILD_NUMBER}.zip build/jcms-*.bin build/jcms-*.txt
  - md5sum jcms-build${APPVEYOR_BUILD_NUMBER}.zip >jcms-build${APPVEYOR_BUILD_NUMBER}-md5sum.txt

artifacts:
  - path: 'jcms-build*.zip'
  - path: 'jcms-build*-md5sum.txt'

test: off

deploy: off
